/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/lock_open.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const IconData emojismile =
      IconData(0xe800, fontFamily: 'emojismile', fontPackage: null);
  static const IconData bullhorn =
      IconData(0xe801, fontFamily: 'bullhorn', fontPackage: null);
  static const IconData lockOpen =
      IconData(0xe800, fontFamily: 'lockOpen', fontPackage: null);
  static const IconData heart =
      IconData(0xe800, fontFamily: 'heart', fontPackage: null);
  static const IconData questionMark =
      IconData(0xe800, fontFamily: 'questionMark', fontPackage: null);
  static const IconData discount =
      IconData(0xe800, fontFamily: 'discount', fontPackage: null);
  static const IconData gift =
      IconData(0xe800, fontFamily: 'gift', fontPackage: null);
  static const IconData cardGift =
      IconData(0xe800, fontFamily: 'cardGift', fontPackage: null);
  static const IconData cash =
      IconData(0xe803, fontFamily: 'cash', fontPackage: null);
  static const IconData bank =
      IconData(0xf19c, fontFamily: 'bank', fontPackage: null);
  static const IconData directionWalk =
      IconData(0xe801, fontFamily: 'directionWalk', fontPackage: null);
  static const IconData assignment =
      IconData(0xe800, fontFamily: 'assignment', fontPackage: null);
  static const IconData shopping =
      IconData(0xe800, fontFamily: 'shopping', fontPackage: null);
  static const IconData ticket =
      IconData(0xe800, fontFamily: 'ticket', fontPackage: null);
  static const IconData emoticonExcited =
      IconData(0xe800, fontFamily: 'emoticonExcited', fontPackage: null);
  static const IconData tagTextOutline =
      IconData(0xe800, fontFamily: 'tagTextOutline', fontPackage: null);
  static const IconData cards =
      IconData(0xe800, fontFamily: 'cards', fontPackage: null);
  static const IconData thumbUpOutline =
      IconData(0xe800, fontFamily: 'thumbUpOutline', fontPackage: null);
  static const IconData cartOff =
      IconData(0xe800, fontFamily: 'cartOff', fontPackage: null);
  static const IconData accountKey =
      IconData(0xe800, fontFamily: 'accountKey', fontPackage: null);
  static const IconData keyboardVariant =
      IconData(0xe800, fontFamily: 'keyboardVariant', fontPackage: null);
  static const IconData up =
      IconData(0xe800, fontFamily: 'up', fontPackage: null);
  static const IconData checked =
      IconData(0xe800, fontFamily: 'checked', fontPackage: null);
  static const IconData checkOutline =
      IconData(0xe800, fontFamily: 'checkOutline', fontPackage: null);
  static const IconData fork =
      IconData(0xe800, fontFamily: 'fork', fontPackage: null);
  static const IconData sword =
      IconData(0xe800, fontFamily: 'sword', fontPackage: null);
  static const IconData cash100 =
      IconData(0xe800, fontFamily: 'cash100', fontPackage: null);
  static const IconData gavel =
      IconData(0xe800, fontFamily: 'gavel', fontPackage: null);
  static const IconData trendingUp =
      IconData(0xe800, fontFamily: 'trendingUp', fontPackage: null);
  static const IconData foodForkDrink =
      IconData(0xe800, fontFamily: 'foodForkDrink', fontPackage: null);
  static const IconData accountGroup =
      IconData(0xe800, fontFamily: 'accountGroup', fontPackage: null);
  static const IconData earth =
      IconData(0xe800, fontFamily: 'earth', fontPackage: null);
  static const IconData human =
      IconData(0xe800, fontFamily: 'human', fontPackage: null);
  static const IconData broom =
      IconData(0xe800, fontFamily: 'broom', fontPackage: null);
  static const IconData menuIcon =
      IconData(0xe803, fontFamily: 'menu_icon', fontPackage: null);
  static const IconData switchIcon =
      IconData(0xe800, fontFamily: 'switch_icon', fontPackage: null);
}
