//dart
export 'dart:async';
export 'dart:collection';
export 'dart:convert';
export 'dart:io';
export 'dart:math';
export 'dart:typed_data';

export 'package:flutter/foundation.dart' show SynchronousFuture;
//dependencies
export 'package:flutter/material.dart';
export 'package:flutter/rendering.dart';
export 'package:flutter/services.dart';
export 'package:flutter_localizations/flutter_localizations.dart';

// export '../activity/model/activity_three.dart';
// export '../activity/model/activity_two.dart';
// export '../activity/view/activity_four_layout.dart';
// //activity
// export '../activity/view/activity_one_layout.dart';
// export '../activity/view/activity_three_layout.dart';
// export '../activity/view/activity_two_layout.dart';
// export '../calendar/color/calendar_four_color.dart';
// export '../calendar/color/calendar_one_color.dart';
// export '../calendar/color/calendar_three_color.dart';
// export '../calendar/color/calendar_two_color.dart';
// export '../calendar/model/calendar.dart';
// export '../calendar/model/calendar_four.dart';
// export '../calendar/model/calendar_one.dart';
// export '../calendar/model/calendar_three.dart';
// export '../calendar/model/calendar_two.dart';
// export '../calendar/view/calendar_four_layout.dart';
// //calendar
// export '../calendar/view/calendar_one_layout.dart';
// export '../calendar/view/calendar_three_layout.dart';
// export '../calendar/view/calendar_two_layout.dart';
// export '../cart/color/cart_five_color.dart';
// export '../cart/color/cart_four_color.dart';
// export '../cart/color/cart_one_color.dart';
// export '../cart/color/cart_seven_color.dart';
// export '../cart/color/cart_six_color.dart';
// export '../cart/color/cart_three_color.dart';
// export '../cart/color/cart_two_color.dart';
// export '../cart/model/cart_five.dart';
// export '../cart/model/cart_four.dart';
// export '../cart/model/cart_seven.dart';
// export '../cart/model/cart_six.dart';
// export '../cart/model/cart_three.dart';
// export '../cart/view/cart_five_layout.dart';
// export '../cart/view/cart_four_layout.dart';
// export '../cart/view/cart_four_list_layout.dart';
// //cart
// export '../cart/view/cart_one_layout.dart';
// export '../cart/view/cart_seven_layout.dart';
// export '../cart/view/cart_seven_list_layout.dart';
// export '../cart/view/cart_six_layout.dart';
// export '../cart/view/cart_three_layout.dart';
// export '../cart/view/cart_three_list_layout.dart';
// export '../checkout/color/checkout_eight_color.dart';
// export '../checkout/color/checkout_five_color.dart';
// export '../checkout/color/checkout_four_color.dart';
// export '../checkout/color/checkout_one_color.dart';
// export '../checkout/color/checkout_seven_color.dart';
// export '../checkout/color/checkout_six_color.dart';
// export '../checkout/color/checkout_three_color.dart';
// export '../checkout/color/checkout_two_color.dart';
// export '../checkout/model/checkout_eight.dart';
// export '../checkout/model/checkout_five.dart';
// export '../checkout/model/checkout_one.dart';
// export '../checkout/model/checkout_seven.dart';
// export '../checkout/model/checkout_six.dart';
// export '../checkout/model/checkout_three.dart';
// export '../checkout/model/checkout_two.dart';
// export '../checkout/view/checkout_eight_item_layout.dart';
// export '../checkout/view/checkout_eight_layout.dart';
// export '../checkout/view/checkout_five_layout.dart';
// export '../checkout/view/checkout_four_layout.dart';
// //checkout
// export '../checkout/view/checkout_one_layout.dart';
// export '../checkout/view/checkout_seven_item_layout.dart';
// export '../checkout/view/checkout_seven_layout.dart';
// export '../checkout/view/checkout_six_layout.dart';
// export '../checkout/view/checkout_three_layout.dart';
// export '../checkout/view/checkout_two_layout.dart';
// export '../content_screen/color/content_five_color.dart';
// export '../content_screen/color/content_four_color.dart';
// export '../content_screen/color/content_one_color.dart';
// export '../content_screen/color/content_six_color.dart';
// export '../content_screen/color/content_three_color.dart';
// export '../content_screen/color/content_two_color.dart';
// export '../content_screen/model/content_five.dart';
// export '../content_screen/model/content_four.dart';
// export '../content_screen/model/content_one.dart';
// export '../content_screen/model/content_six.dart';
// export '../content_screen/model/content_three.dart';
// export '../content_screen/model/content_two.dart';
// export '../content_screen/view/content_five_layout.dart';
// export '../content_screen/view/content_four_layout.dart';
// //content screen
// export '../content_screen/view/content_one_layout.dart';
// export '../content_screen/view/content_six_layout.dart';
// export '../content_screen/view/content_three_layout.dart';
// export '../content_screen/view/content_three_stories_layout.dart';
// export '../content_screen/view/content_two_layout.dart';
// export '../discover/color/discover_four_one_eight_color.dart';
// export '../discover/color/discover_four_one_nine_color.dart';
// export '../discover/color/discover_four_one_seven_color.dart';
// export '../discover/color/discover_four_one_six_color.dart';
// export '../discover/color/discover_four_two_one_color.dart';
// export '../discover/color/discover_four_two_three_color.dart';
// export '../discover/color/discover_four_two_two_color.dart';
// export '../discover/color/discover_four_two_zero_color.dart';
// export '../discover/model/discover_four_one_eight.dart';
// export '../discover/model/discover_four_one_nine.dart';
// export '../discover/model/discover_four_one_seven.dart';
// export '../discover/model/discover_four_one_six.dart';
// export '../discover/model/discover_four_two_one.dart';
// export '../discover/model/discover_four_two_three.dart';
// export '../discover/model/discover_four_two_two.dart';
// export '../discover/model/discover_four_two_zero.dart';
// export '../discover/view/discover_four_one_eight_layout.dart';
// export '../discover/view/discover_four_one_nine_layout.dart';
// export '../discover/view/discover_four_one_seven_layout.dart';
// //discover
// export '../discover/view/discover_four_one_six_layout.dart';
// export '../discover/view/discover_four_two_one_layout.dart';
// export '../discover/view/discover_four_two_three_layout.dart';
// export '../discover/view/discover_four_two_two_layout.dart';
// export '../discover/view/discover_four_two_zero_layout.dart';
// export '../filter/color/page_four_zero_five_color.dart';
// export '../filter/color/page_four_zero_six_color.dart';
// export '../filter/color/page_four_zero_three_color.dart';
// export '../filter/color/page_four_zero_two_color.dart';
// export '../filter/model/page_four_one_three.dart';
// export '../filter/model/page_four_zero_seven.dart';
// export '../filter/model/page_four_zero_three.dart';
// export '../filter/view/bottom_layout.dart';
// export '../filter/view/menu_filter_layout.dart';
// //filter
// export '../filter/view/page_four_one_three_layout.dart';
// export '../filter/view/page_four_zero_five_layout.dart';
// export '../filter/view/page_four_zero_seven_grid_camera_item_layout.dart';
// export '../filter/view/page_four_zero_seven_grid_camera_layout.dart';
// export '../filter/view/page_four_zero_seven_grid_clock_item_layout.dart';
// export '../filter/view/page_four_zero_seven_grid_clock_layout.dart';
// export '../filter/view/page_four_zero_seven_layout.dart';
// export '../filter/view/page_four_zero_six_layout.dart';
// export '../filter/view/page_four_zero_three_layout.dart';
// export '../filter/view/page_four_zero_two_layout.dart';
// export '../first_second/color/first_screen_color.dart';
// export '../first_second/color/second_screen_color.dart';
// export '../first_second/model/first_screen.dart';
// export '../first_second/model/second_screen.dart';
// export '../first_second/view/first_screen_grid_item_layout.dart';
// export '../first_second/view/first_screen_grid_layout.dart';
// export '../first_second/view/first_screen_horizontal_item_layout.dart';
// //sample
// export '../first_second/view/first_screen_layout.dart';
// export '../first_second/view/first_screen_vertical_item_layout.dart';
// export '../first_second/view/second_screen_layout.dart';
// export '../home/color/home_color.dart';
// export '../home/color/theme_color.dart';
// export '../home/model/home.dart';
// //home
// export '../home/view/home_layout.dart';
// export '../home/view/theme_layout.dart';
// export '../login/color/login_eight_color.dart';
// export '../login/color/login_five_color.dart';
// export '../login/color/login_four_color.dart';
// export '../login/color/login_one_color.dart';
// export '../login/color/login_seven_color.dart';
// export '../login/color/login_six_color.dart';
// export '../login/color/login_three_color.dart';
// export '../login/color/login_two_color.dart';
// export '../login/view/login_eight_layout.dart';
// export '../login/view/login_five_layout.dart';
// export '../login/view/login_four_layout.dart';
// //login
// export '../login/view/login_one_layout.dart';
// export '../login/view/login_seven_layout.dart';
// export '../login/view/login_six_layout.dart';
// export '../login/view/login_three_layout.dart';
// export '../login/view/login_two_layout.dart';
// export '../map/color/map_four_color.dart';
// export '../map/color/map_one_color.dart';
// export '../map/color/map_three_color.dart';
// export '../map/color/map_two_color.dart';
// export '../map/model/map_four.dart';
// export '../map/model/map_one.dart';
// export '../map/model/map_two.dart';
// export '../map/view/map_four_layout.dart';
// //map
// export '../map/view/map_one_layout.dart';
// export '../map/view/map_three_item_layout.dart';
// export '../map/view/map_three_layout.dart';
// export '../map/view/map_two_item_layout.dart';
// export '../map/view/map_two_layout.dart';
// export '../navigation/color/navigation_five_color.dart';
// export '../navigation/color/navigation_four_color.dart';
// export '../navigation/color/navigation_one_color.dart';
// export '../navigation/color/navigation_three_color.dart';
// export '../navigation/model/navigation_five.dart';
// export '../navigation/model/navigation_four.dart';
// export '../navigation/model/navigation_one.dart';
// export '../navigation/model/navigation_three.dart';
// export '../navigation/model/navigation_two.dart';
// export '../navigation/view/navigation_five_layout.dart';
// export '../navigation/view/navigation_four_layout.dart';
// //navigation
// export '../navigation/view/navigation_one_layout.dart';
// export '../navigation/view/navigation_three_layout.dart';
// export '../navigation/view/navigation_two_layout.dart';
// export '../product/color/product_eight_color.dart';
// export '../product/color/product_eighteen_color.dart';
// export '../product/color/product_eleven_color.dart';
// export '../product/color/product_fifteen_color.dart';
// export '../product/color/product_five_color.dart';
// export '../product/color/product_four_color.dart';
// export '../product/color/product_fourteen_color.dart';
// export '../product/color/product_nine_color.dart';
// export '../product/color/product_nineteen_color.dart';
// export '../product/color/product_one_color.dart';
// export '../product/color/product_seventeen_color.dart';
// export '../product/color/product_six_color.dart';
// export '../product/color/product_sixteen_color.dart';
// export '../product/color/product_ten_color.dart';
// export '../product/color/product_three_color.dart';
// export '../product/color/product_twelve_color.dart';
// export '../product/color/product_two_color.dart';
// export '../product/model/product_eight.dart';
// export '../product/model/product_eighteen.dart';
// export '../product/model/product_eleven.dart';
// export '../product/model/product_fifteen.dart';
// export '../product/model/product_five.dart';
// export '../product/model/product_four.dart';
// export '../product/model/product_fourteen.dart';
// export '../product/model/product_nine.dart';
// export '../product/model/product_nineteen.dart';
// export '../product/model/product_one.dart';
// export '../product/model/product_seven.dart';
// export '../product/model/product_seventeen.dart';
// export '../product/model/product_six.dart';
// export '../product/model/product_sixteen.dart';
// export '../product/model/product_ten.dart';
// export '../product/model/product_thirteen.dart';
// export '../product/model/product_three.dart';
// export '../product/model/product_twelve.dart';
// export '../product/model/product_two.dart';
// export '../product/view/product_eight_layout.dart';
// export '../product/view/product_eighteen_layout.dart';
// export '../product/view/product_eleven_layout.dart';
// export '../product/view/product_fifteen_layout.dart';
// export '../product/view/product_five_layout.dart';
// export '../product/view/product_four_layout.dart';
// export '../product/view/product_fourteen_layout.dart';
// export '../product/view/product_nine_layout.dart';
// export '../product/view/product_nineteen_layout.dart';
// //product
// export '../product/view/product_one_layout.dart';
// export '../product/view/product_seven_layout.dart';
// export '../product/view/product_seventeen_layout.dart';
// export '../product/view/product_six_layout.dart';
// export '../product/view/product_sixteen_layout.dart';
// export '../product/view/product_ten_layout.dart';
// export '../product/view/product_thirteen_layout.dart';
// export '../product/view/product_three_layout.dart';
// export '../product/view/product_twelve_layout.dart';
// export '../product/view/product_two_layout.dart';
// export '../profile/color/profile_eight_color.dart';
// export '../profile/color/profile_five_color.dart';
// export '../profile/color/profile_four_color.dart';
// export '../profile/color/profile_nine_color.dart';
// export '../profile/color/profile_one_color.dart';
// export '../profile/color/profile_seven_color.dart';
// export '../profile/color/profile_six_color.dart';
// export '../profile/color/profile_ten_color.dart';
// export '../profile/color/profile_three_color.dart';
// export '../profile/color/profile_two_color.dart';
// export '../profile/model/profile_five.dart';
// export '../profile/model/profile_one.dart';
// export '../profile/model/profile_three.dart';
// export '../profile/model/profile_two.dart';
// export '../profile/view/profile_eight_layout.dart';
// export '../profile/view/profile_five_layout.dart';
// export '../profile/view/profile_four_layout.dart';
// export '../profile/view/profile_nine_layout.dart';
// //profile
// export '../profile/view/profile_one_layout.dart';
// export '../profile/view/profile_seven_layout.dart';
// export '../profile/view/profile_six_layout.dart';
// export '../profile/view/profile_ten_layout.dart';
// export '../profile/view/profile_three_layout.dart';
// export '../profile/view/profile_two_layout.dart';
// export '../promo/color/promo_five_color.dart';
// export '../promo/color/promo_four_color.dart';
// export '../promo/color/promo_one_color.dart';
// export '../promo/color/promo_six_color.dart';
// export '../promo/color/promo_three_color.dart';
// export '../promo/color/promo_two_color.dart';
// export '../promo/model/promo_five.dart';
// export '../promo/model/promo_four.dart';
// export '../promo/model/promo_one.dart';
// export '../promo/model/promo_six.dart';
// export '../promo/model/promo_three.dart';
// export '../promo/model/promo_two.dart';
// export '../promo/view/promo_five_layout.dart';
// export '../promo/view/promo_four_layout.dart';
// //promo
// export '../promo/view/promo_one_layout.dart';
// export '../promo/view/promo_six_layout.dart';
// export '../promo/view/promo_three_layout.dart';
// export '../promo/view/promo_two_layout.dart';
// export '../social/color/social_eight_color.dart';
// export '../social/color/social_five_color.dart';
// export '../social/color/social_four_color.dart';
// export '../social/color/social_nine_color.dart';
// export '../social/color/social_one_color.dart';
// export '../social/color/social_seven_color.dart';
// export '../social/color/social_six_color.dart';
// export '../social/color/social_three_color.dart';
// export '../social/color/social_two_color.dart';
// export '../social/model/social_eight.dart';
// export '../social/model/social_five.dart';
// export '../social/model/social_four.dart';
// export '../social/model/social_nine.dart';
// export '../social/model/social_one.dart';
// export '../social/model/social_seven.dart';
// export '../social/model/social_six.dart';
// export '../social/model/social_three.dart';
// export '../social/model/social_two.dart';
// export '../social/view/social_eight_grid_item_layout.dart';
// export '../social/view/social_eight_grid_layout.dart';
// export '../social/view/social_eight_layout.dart';
// export '../social/view/social_five_item_layout.dart';
// export '../social/view/social_five_layout.dart';
// export '../social/view/social_four_item_layout.dart';
// export '../social/view/social_four_layout.dart';
// export '../social/view/social_nine_layout.dart';
// export '../social/view/social_one_item_layout.dart';
// //social
// export '../social/view/social_one_layout.dart';
// export '../social/view/social_seven_item_layout.dart';
// export '../social/view/social_seven_layout.dart';
// export '../social/view/social_six_item_layout.dart';
// export '../social/view/social_six_layout.dart';
// export '../social/view/social_three_item_layout.dart';
// export '../social/view/social_three_layout.dart';
// export '../social/view/social_two_item_layout.dart';
// export '../social/view/social_two_layout.dart';
// export '../wish_list/color/wish_eight_color.dart';
// export '../wish_list/color/wish_eleven_color.dart';
// export '../wish_list/color/wish_fifteen_color.dart';
// export '../wish_list/color/wish_five_color.dart';
// export '../wish_list/color/wish_four_color.dart';
// export '../wish_list/color/wish_fourteen_color.dart';
// export '../wish_list/color/wish_nine_color.dart';
// export '../wish_list/color/wish_one_color.dart';
// export '../wish_list/color/wish_seven_color.dart';
// export '../wish_list/color/wish_six_color.dart';
// export '../wish_list/color/wish_ten_color.dart';
// export '../wish_list/color/wish_thirteen_color.dart';
// export '../wish_list/color/wish_three_color.dart';
// export '../wish_list/color/wish_twelve_color.dart';
// export '../wish_list/color/wish_two_color.dart';
// export '../wish_list/model/wish_eight.dart';
// export '../wish_list/model/wish_eleven.dart';
// export '../wish_list/model/wish_fifteen.dart';
// export '../wish_list/model/wish_five.dart';
// export '../wish_list/model/wish_four.dart';
// export '../wish_list/model/wish_fourteen.dart';
// export '../wish_list/model/wish_nine.dart';
// export '../wish_list/model/wish_one.dart';
// export '../wish_list/model/wish_seven.dart';
// export '../wish_list/model/wish_six.dart';
// export '../wish_list/model/wish_ten.dart';
// export '../wish_list/model/wish_thirteen.dart';
// export '../wish_list/model/wish_twelve.dart';
// export '../wish_list/model/wish_two.dart';
// export '../wish_list/view/wish_eight_layout.dart';
// export '../wish_list/view/wish_eleven_layout.dart';
// export '../wish_list/view/wish_fifteen_layout.dart';
// export '../wish_list/view/wish_five_layout.dart';
// export '../wish_list/view/wish_four_layout.dart';
// export '../wish_list/view/wish_fourteen_layout.dart';
// export '../wish_list/view/wish_nine_layout.dart';
// //wish list
// export '../wish_list/view/wish_one_layout.dart';
// export '../wish_list/view/wish_seven_layout.dart';
// export '../wish_list/view/wish_six_layout.dart';
// export '../wish_list/view/wish_ten_layout.dart';
// export '../wish_list/view/wish_thirteen_layout.dart';
// export '../wish_list/view/wish_three_layout.dart';
// export '../wish_list/view/wish_twelve_layout.dart';
// export '../wish_list/view/wish_two_layout.dart';
export 'asset/asset_key.dart';
export 'color/card_color.dart';
export 'color/cart_add_minus_list_color.dart';
export 'color/cart_empty_color.dart';
export 'color/cart_list_color.dart';
export 'color/checkout_process_color.dart';
export 'color/color_key.dart';
export 'color/custom_switch_color.dart';
export 'color/discount_coupon_color.dart';
export 'color/filter_color.dart';
export 'color/grid_item_color.dart';
export 'color/horizontal_item_color.dart';
export 'color/item_found_color.dart';
export 'color/list_tile_color.dart';
export 'color/menu_filter_color.dart';
export 'color/navigation_drawer_color.dart';
export 'color/navigation_list_color.dart';
export 'color/original_total_color.dart';
export 'color/price_summary_color.dart';
export 'color/product_color.dart';
export 'color/product_color_detail_color.dart';
export 'color/product_color_size_color.dart';
export 'color/product_delivery_color.dart';
export 'color/product_detail_color.dart';
export 'color/product_item_description_color.dart';
export 'color/product_list_tile_and_item_details_color.dart';
export 'color/product_nutrition_color.dart';
export 'color/product_single_color.dart';
export 'color/product_size_color.dart';
export 'color/product_size_detail_color.dart';
export 'color/product_three_list_tile_color.dart';
export 'color/product_topping_color.dart';
export 'color/product_topping_detail_color.dart';
export 'color/product_total_price_color.dart';
export 'color/project_color.dart';
export 'color/promotion_code_color.dart';
export 'color/search_color.dart';
export 'color/second_card_color.dart';
export 'color/top_deal_with_cart_color.dart';
export 'color/top_detail_color.dart';
export 'color/vertical_item_color.dart';
export 'color/wish_button_delete_color.dart';
export 'color/wish_grid_checkout_color.dart';
export 'color/wish_grid_item_color.dart';
export 'color/wish_grid_item_selection_color.dart';
export 'color/wish_item_color.dart';
export 'color/wish_item_select_color.dart';
export 'color/wish_move_color.dart';
export 'color/wish_table_color.dart';
export 'icon/custom_icon.dart';
export 'listener/theme_listener.dart';
export 'localization/app_localization.dart';
export 'localization/app_localization_delegate.dart';
export 'localization/language.dart';
export 'localization/language_key.dart';
export 'model/constant.dart';
export 'model/discount.dart';
export 'model/item_found.dart';
export 'model/no_item.dart';
export 'model/product_detail.dart';
export 'model/themes.dart';
export 'theme/dark_theme.dart';
export 'theme/light_theme.dart';
export 'utilities/alert_dialog_utilities.dart';
//base
export 'utilities/color_utilities.dart';
export 'utilities/common_utilities.dart';
export 'utilities/navigation_slide_transition_utilities.dart';
// export 'utilities/view_utilities.dart';
export 'view/base_layout.dart';
export 'view/cart_add_minus_list_layout.dart';
export 'view/cart_checkout_button_layout.dart';
// export 'view/cart_empty_layout.dart';
export 'view/checkout_process_layout.dart';
export 'view/custom_slider.dart';
// export 'view/custom_switch.dart';
export 'view/dash_seperator.dart';
export 'view/discover_layout.dart';
// export 'view/expanded_section.dart';
// export 'view/filter_layout.dart';
export 'view/item_found_layout.dart';
// export 'view/list_pill_button_layout.dart';
// export 'view/list_tile_layout.dart';
// export 'view/navigation_drawer_layout.dart';
// export 'view/navigation_list_layout.dart';
//search
// export 'view/no_item_layout.dart';
export 'view/order_total_layout.dart';
export 'view/price_summary_layout.dart';
export 'view/product_bottom_add_minus_layout.dart';
// export 'view/product_color_detail_layout.dart';
// export 'view/product_color_layout.dart';
// export 'view/product_color_size_layout.dart';
// export 'view/product_delivery_layout.dart';
// export 'view/product_detail_layout.dart';
export 'view/product_item_description_layout.dart';
// export 'view/product_list_tile_and_item_details_layout.dart';
// export 'view/product_nutrition_layout.dart';
// export 'view/product_single_layout.dart';
// export 'view/product_size_detail_layout.dart';
// export 'view/product_size_layout.dart';
// export 'view/product_three_list_tile_layout.dart';
// export 'view/product_topping_detail.dart';
// export 'view/product_topping_layout.dart';
// export 'view/product_total_price_layout.dart';
// export 'view/profile_image_layout.dart';
// export 'view/promotion_code_layout.dart';
// export 'view/purple_toolbar_layout.dart';
// export 'view/scaffold_layout.dart';
// export 'view/search_field_layout.dart';
// export 'view/search_layout.dart';
export 'view/slider_dot_layout.dart';
// export 'view/slider_layout.dart';
// export 'view/tab_above_layout.dart';
// export 'view/tab_bar_and_tab_view_layout.dart';
// export 'view/tab_below_layout.dart';
// export 'view/top_deal_with_cart_layout.dart';
// export 'view/wish_button_delete_layout.dart';
// export 'view/wish_grid_checkbox_layout.dart';
// export 'view/wish_grid_item_layout.dart';
// export 'view/wish_grid_item_selection_layout.dart';
// export 'view/wish_item_layout.dart';
// export 'view/wish_item_select_layout.dart';
// export 'view/wish_move_layout.dart';
// export 'view/wish_table_layout.dart';
